
# parent image
FROM alpine:3.7

# copy python requirements file
COPY requirements.txt /tmp/requirements.txt

# OS installs, pip installs, etc. (https://pkgs.alpinelinux.org/packages)
RUN apk add --no-cache \
    python3=3.6.3-r9 \
    nodejs=8.9.3-r0 \
    nodejs-npm=8.9.3-r0 \
    bash=4.4.19-r1 \
    supervisor=3.3.3-r1 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install pip setuptools==38.5.1 && \
    pip3 install -r /tmp/requirements.txt

# custom Supervisord config
COPY config/supervisord.dev.conf /etc/supervisord.conf

# npm installs
COPY app/client/package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /app/client && cp -a /tmp/node_modules /app/client/

# the rest is handled by the docker-compose.yml file
