
version: '3'


services:

  flask-vue-frontend:
    build:
      context: ./app/client
      dockerfile: 'Dockerfile'
    image: flask-vue-frontend:dev
    container_name: flask-vue-frontend-dev
    restart: always
    ports:
     - "8080:8080"
    volumes:
     - ./app/client:/client
    command: 'npm run serve'

  flask-vue-backend:
    build:
      context: ./app/server
      dockerfile: 'Dockerfile'
    image: flask-vue-backend:dev
    container_name: flask-vue-backend-dev
    restart: always
    links:
      - flask-vue-mysql:mysql
      - flask-vue-redis:redis
    ports:
     - "8000:8000"
    volumes:
     - ./app/server:/server
    environment:
     - FLASK_APP=main.py
     - FLASK_DEBUG=1
    command: 'flask run --host=0.0.0.0 --port=8000'

  flask-vue-mysql:
    image: mysql:5.7
    container_name: flask-vue-mysql-dev
    restart: always
    volumes:
     - ./mysql_store_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flask_vue_project_seed

  flask-vue-adminer:
    image: adminer:4.6.2
    container_name: flask-vue-adminer-dev
    restart: always
    links:
      - flask-vue-mysql:mysql
    ports:
      - "5000:8080"

  flask-vue-redis:
    image: redis:4.0.9-alpine
    container_name: flask-vue-redis-dev
    restart: always
    volumes:
     - ./redis_store_dev:/data

