
version: '3'


services:

  webapp-dev:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: flask-vue:dev
    container_name: flask-vue-dev
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    ports:
     - "4000:4000"
    volumes:
     - ./app:/app
     - /app/client/node_modules
    environment:
    # flask vars
     - FLASK_HOST=0.0.0.0
     - FLASK_PORT=80
     - FLASK_APP=server/main.py
     - FLASK_DEBUG=1
    # webpack server host and port
     - HOST=0.0.0.0
     - PORT=4000
    # command: /usr/bin/supervisord
    command: 'flask run --host=0.0.0.0 --port=4000'

  mysql:
    image: mysql:5.7
    container_name: flask-vue-mysql-dev
    restart: always
    volumes:
     - ./mysql_store_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flask_vue_project_seed

  adminer:
    image: adminer:4.6.2
    container_name: flask-vue-adminer-dev
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0.9-alpine
    container_name: flask-vue-redis-dev
    restart: always
    volumes:
     - ./redis_store_dev:/data

